### ISSUE TITLE
Add To Combined Library

### ISSUE THREAD

**Issue by prescottprue** [AndersDJohnson/firedux#36]
There are many libraries that provide functionality similar to this one.
## Existing Libraries
- [firedux](https://github.com/adjohnson916/firedux) - supports v3.0.4
- [redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase) - Current defacto solution but owner is busy for a few months
- [refire](https://www.npmjs.com/package/refire) - easily configurable firebase bindings
- [redux-firebase](https://github.com/colbyr/redux-firebase) - best namespace
- [react-firebase](https://github.com/unfold/react-firebase) - Similar to react-redux, good docs

Though it is nice to have different libraries with different implementations, some of the library authors were thinking of combining the best of all of them into one defacto solution. Would you be interested in joining the group of us creating this firebase-redux integration? Your solution is beautiful, and we would love your input with creating a combined library.

Here are the issues posted for the other libraries:

[redux-firebase](https://github.com/colbyr/redux-firebase/issues/2)
[redux-react-firebase](https://github.com/tiberiuc/redux-react-firebase/issues/23)

Thoughts?

**Comment by prescottprue** [comment]
Not sure if you are on the [Firebase Slack](firebase-community.slack.com), but there is a Redux channel there. Might be good to have discussion there so we don't have to leave an issue open on your repo.

**Comment by adjohnson916** [comment]
@prescottprue Sure, I'd be interested in working together on a de facto solution. Time, not interest, would be the primary constraint in my involvement. Some of the other libraries seem to have some aspects of deeper React & ES6 integration, which I do like.

I'm not on the Firebase Slack, do I need an invite to join?

**Comment by adjohnson916** [comment]
See https://github.com/colbyr/redux-firebase/issues/2.

**Comment by adjohnson916** [comment]
See https://github.com/tiberiuc/redux-react-firebase/issues/23.
